[package]
name = "dm_lfo"
version = "0.1.0"
edition = "2021"

[dependencies]
lv2 = { git = "https://github.com/davemollen/rust-lv2.git", features = [
    "minimal_plugin",
] }
lfo = { path = "../lfo" }

[lib]
crate-type = ["cdylib"]
